export enum Region {
    Nederland = 0,
    Groningen = 1,
    Friesland = 2,
    Drenthe = 3,
    Overijssel = 4,
    Flevoland = 5,
    Gelderland = 6,
    Utrecht = 7,
    NoordHolland = 8,
    ZuidHolland = 9,
    Zeeland = 10,
    NoordBrabant = 11,
    Limburg = 12,
    Offshore = 14,
    WindparkLuchterduinen = 28,
    WindparkPrincesAmalia = 29,
    WindparkEgmondaanZee = 30,
    WindparkGemini = 31,
    WindparkBorselleI_II = 33,
    WindparkBorselleIII_IV = 34,
    WindparkHollandseKustZuid = 35,
    WindparkHollandseKustNoord = 36
}